name: navigating asymmetricality
favicon: null
layout_spectrum: 0.40417950600385666
typography_spectrum: 0.601405295310542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3971953096333891
  lightness: 0.9525618925690651
  saturation: 0.24738210975192487
  rhythmicContrast: 0.5579003288876265
purpose: []
